CREATE TABLE `board_database`.`board` (
  `SEQ` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `SUBJECT` VARCHAR(100) NULL,
  `CONTENT` LONGTEXT NULL,
  `REG_DT` TIMESTAMP NULL,
  `REG_NAME` VARCHAR(45) NULL
) ENGINE=INNODB AUTO_INCREMENT=1 COLLATE=utf8mb4_unicode_ci
;